baseURL = "https://naif.soy"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Naif Alzahri"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
publishDir = "docs"
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/


[author]
  name = "Naif"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "Web Developer/Data Scientist"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

# look here github.com/Track3/hermit#social-icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/Nayifff"

  [[params.social]]
    name = "email"
    url = "naif.a@columbia.edu"
